In [1]:
import numpy as np

In [22]:
x = np.array([[12,9,2], [3,17,2], [21, 0, 0], [9,4,8]])

In [4]:
np.sum(x, axis=1)

array([23, 22, 21, 21])

In [5]:
np.sum(x, axis=0)

array([45, 30, 12])

In [6]:
x.sum(axis=0)

array([45, 30, 12])

In [7]:
x.sum()

87

In [23]:
y = np.ones((3,1))

In [12]:
x.shape

(4, 3)

In [25]:
np.dot(x, y)

array([[ 23.],
       [ 22.],
       [ 21.],
       [ 21.]])

In [24]:
x.dot(y).ravel()
#x.resize()

array([ 23.,  22.,  21.,  21.])

In [16]:
x@y

array([[ 23.],
       [ 22.],
       [ 21.],
       [ 21.]])

In [26]:
z=np.ones((1,4))

In [27]:
z@x

array([[ 45.,  30.,  12.]])

In [28]:
x.ravel()

array([12,  9,  2,  3, 17,  2, 21,  0,  0,  9,  4,  8])

In [29]:
x@np.array([1,-1,0])

array([  3, -14,  21,   5])

In [30]:
x[0]

array([12,  9,  2])

In [31]:
x[0:2]

array([[12,  9,  2],
       [ 3, 17,  2]])

In [32]:
x[:,0]
#нулевой элемент каждой строки

array([12,  3, 21,  9])

In [33]:
x[:,0] > x[:,1]

array([ True, False,  True,  True], dtype=bool)

In [34]:
w = np.array([[0,11,12],[21,0,0]])

In [35]:
w

array([[ 0, 11, 12],
       [21,  0,  0]])

In [46]:
#np.hstack
#np.vstack
#np.concatenate
u = np.vstack((x,w))

In [38]:
q = np.ones((4,1))

In [40]:
e = np.zeros((2,1))

In [48]:
t = np.vstack((q,e))

In [49]:
t = np.array([1, 1, 1, 1, 0, 0])

In [50]:
t.shape

(6,)

In [57]:
t[:, np.newaxis].shape

(6, 1)

In [63]:
matrix = np.hstack((u,t[:, np.newaxis]))

In [51]:
x_sum = x.sum(axis=1)

In [52]:
x_sum

array([23, 22, 21, 21])

In [53]:
x_sum.shape

(4,)

In [54]:
x_sum[:, np.newaxis]

array([[23],
       [22],
       [21],
       [21]])

In [56]:
x.shape, x_sum[:, np.newaxis].shape

((4, 3), (4, 1))

In [61]:
x[[2,1]]

array([[21,  0,  0],
       [ 3, 17,  2]])

In [62]:
np.random.permutation(x)

array([[ 9,  4,  8],
       [ 3, 17,  2],
       [12,  9,  2],
       [21,  0,  0]])

In [64]:
np.random.permutation(matrix)

array([[ 3, 17,  2,  1],
       [21,  0,  0,  0],
       [ 9,  4,  8,  1],
       [12,  9,  2,  1],
       [21,  0,  0,  1],
       [ 0, 11, 12,  0]])

In [65]:
index = np.random.permutation(np.arange(6))

In [66]:
index

array([4, 2, 1, 0, 5, 3])

In [69]:
result = matrix[index]

# PANDAS

In [70]:
import pandas as pd

In [72]:
pd.DataFrame(data=result, index=['Q' + str(i) for i in range(1,7)], columns=['yes', 'no', 'ignore', 'label'])

yes  no  ignore  label
Q1    0  11      12      0
Q2   21   0       0      1
Q3    3  17       2      1
Q4   12   9       2      1
Q5   21   0       0      0
Q6    9   4       8      1

In [80]:
data = pd.read_csv("https://raw.githubusercontent.com/iad34/seminars/master/data_sem1.csv", sep=";")

In [81]:
data.loc[5]

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran; Mr. James
Sex                     unknown
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object